version: "3.3"

# 网络配置 #
networks:
  # 新建一个局域网 (其他机器若要访问记得添加路由)
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24

services:

  # Zookeeper 节点 (端口 2181) #
  zookeeper:
    container_name: b-zookeeper
    image: confluentinc/cp-zookeeper:5.1.0
    hostname: zookeeper
    # 端口映射：主机端口:内网端口
    ports:
      - 2181:2181
    networks:
      - net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  # Kafka 节点 (端口 9092) #
  kafka:
    container_name: b-kafka
    image: confluentinc/cp-kafka:5.1.0
    hostname: kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    networks:
      - net
    environment:
      # 此处填写主机网卡 IP 地址 (例如公网 IP)！
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://59.77.13.234:9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Cassandra 节点 (端口 9042) #
  cassandra:
    container_name: b-cassandra
    image: 'bitnami/cassandra:latest'
    hostname: cassandra
    networks:
      net:
        # 固定 IP 地址 - ip 定大一点
        ipv4_address: 172.22.0.197
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    volumes:
      - ./stream-processor/spark-schema.cql:/spark-schema.cql

  # Spark Master 节点 #
  spark-master:
    container_name: b-spark-master
    image: bde2020/spark-master:3.0.0-hadoop3.2-java11
    hostname: spark-master
    healthcheck:
      interval: 5s
      retries: 100
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
      - "4041:4041"
    networks:
      - net
    environment:
      - INIT_DAEMON_STEP=false
      - SPARK_DRIVER_HOST=192.168.1.5
    volumes:
      - ./stream-processor/src/main/resources:/opt/spark-data
      - ./stream-processor/target:/app

  # Spark Worker 节点 #
  spark-worker-1:
    container_name: b-spark-worker-1
    image: bde2020/spark-worker:3.0.0-hadoop3.2-java11
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    networks:
      - net
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ./volume-data/spark/:/opt/spark-data

  # Hadoop Namenode节点 #
  namenode:
    container_name: b-hadoop-namenode
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
    hostname: namenode
    healthcheck:
      interval: 5s
      retries: 100
    networks:
      - net
    ports:
      - 50070:50070
      - 8020:8020
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - ./volume-data/namenode:/hadoop/dfs/name

  # Hadoop Datanode节点 #
  datanode:
    container_name: b-hadoop-datanode
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
    hostname: datanode
    depends_on:
      - namenode
    healthcheck:
      interval: 5s
      retries: 100
    networks:
      - net
    ports:
      - 50075:50075
      - 50010:50010
    environment:
      # 设置 HDFS 的路径 (core-site.xml 中的 fs.defaultFS)
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - ./volume-data/datanode:/hadoop/dfs/data
